name: Waystones
version: '${project.version}'
main: eu.ovmc.waystones.Waystones
api-version: 1.19
authors: [ Bambui_Zepelin ]
description: This is a waystone plugin made to remove the use of commands when teleporting.
