package eu.ovmc.waystones.menusystem.items;

public enum ItemType {
    PAGE_BACK,
    PAGE_FORWARD,
    RETURN_TO_DEATH_LOCATION,
    PRIVATE_WAYSTONE,
    PUBLIC_WAYSTONE,
    OPENED_PRIVATE_WAYSTONE,
    OPENED_PUBLIC_WAYSTONE,
    BROKEN,
    PURCHASE,
    AVAILABLE_WAYSTONES,
    SELECTED,
    BLANK,
    CATEGORY;
}
